name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot -e "CREATE DATABASE mysql_database"

      - uses: actions/checkout@v4
