name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot -e "CREATE DATABASE mysql_database"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Composer Install
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Crate Env file
        run: cp .env.example .env.testing

      - name: Write Env file
        run: |
          echo "DB_HOST=db" >> ./.env.testing
          echo "DB_PORT=3306" >> ./.env.testing
          echo "DB_DATABASE=mysql_database" >> ./.env.testing
          echo "DB_USERNAME=mysql_user" >> ./.env.testing
          echo "DB_PASSWORD=mysql_pw" >> ./.env.testing

      - name: Setup Laravel
        run: |
          php artisan key:generate
          php artisan migrate

      - name: Run Tests
        run: php artisan test
