name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot -e "CREATE DATABASE mysql_database"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Composer Install
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Crate Env file
        run: cd directory
#        run: cp env/.env.testing .env.testing

#      - name: Run Tests
#        run: php artisan test
